### ISSUE TITLE
push url

### ISSUE THREAD

**Issue by raoulguillermo** [buckaroo-it/Magento2_GraphQL#14]
Hi, 

Would it be possible to have a call to send or add a push url to the call?
I can send a return url with the call only the push call is allways made to my {frontendurl}/rest/V1/buckaroo/push which does not exist in our pwa. 

I managed to change it in the code to get it working. But i think there should be a better solution?

**Comment by harli91** [comment]
Hi @raoulguillermo you will need to expose this route to te public in order for the correct payment status be received
